import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  titleContainer: {
    width: 393,
    height: 852,
    backgroundColor: "#ffffff",
    position: "relative",
    overflow: "hidden",
    marginTop: 0,
    marginRight: "auto",
    marginBottom: 0,
    marginLeft: "auto",
  },
  underline: {
    marginTop: 25, // Space between the text and the line
    width: "80%", // Width of the line relative to the screen or title
    height: 1, // Thickness of the line
    backgroundColor: "#d9d9d9", // Color of the line
    alignSelf: "center", // Ensures the line is centered
  },
  formContainer: {
    display: "flex",
    paddingTop: 24,
    paddingRight: 24,
    paddingBottom: 24,
    paddingLeft: 24,
    gap: 24,
    alignItems: "flex-start",
    flexWrap: "nowrap",
    // backgroundColor: "#ffffff",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderWidth: 1,
    borderColor: "#2aa5d5",
    borderStyle: "solid",
    position: "absolute",
    justifyContent: "center",
    top: 170,
    left: 65,
  },
  credentialsContainer: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    alignSelf: "stretch",
    flexShrink: 0,
    flexWrap: "nowrap",
    position: "relative",
  },
  inputContainer: {
    display: "flex",
    paddingTop: 12,
    paddingRight: 16,
    paddingBottom: 12,
    paddingLeft: 16,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
    flexShrink: 0,
    flexWrap: "nowrap",
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    borderWidth: 1,
    borderColor: "#d9d9d9",
    borderStyle: "solid",
    position: "relative",
    overflow: "hidden",
  },
  input: {
    height: 16,
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: "auto",
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 16,
    color: "#b3b3b3",
    position: "relative",
    textAlign: "left",
  },
  titleText: {
    fontSize: 36,
    fontFamily: "Inter",
    fontWeight: "bold",
    textAlign: "center",
    top: 50,
    marginBottom: 20,
  },
  labelHeader: {
    height: 22,
    alignSelf: "stretch",
    flexShrink: 0,
    flexBasis: "auto",
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 22,
    // color: "#1e1e1e",
    position: "relative",
    textAlign: "left",
  },
  additionalOptionsText: {
    marginTop: 10,
    height: 22,
    flexShrink: 0,
    flexBasis: "auto",
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 22,
    color: "#1e1e1e",
    position: "relative",
    textAlign: "left",
    textDecorationLine: "underline",
  },
  additionalOptionsButton: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    alignSelf: "stretch",
    flexShrink: 0,
    flexWrap: "nowrap",
    position: "relative",
  },
  signUp: {
    backgroundColor: "#2C4D76",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: "100%",
    alignItems: "center",
    marginTop: 10,
  },
  signUpButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
});

export default styles;
